[package]
name = "npi"
version = "0.1.0"
authors = ["n0pj <admin@n0pj.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
